### ISSUE TITLE
2.1.2 Add redirect URL (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#1]
In the section below, please make it clearer in the text (I know there is already an image) that the user needs to concatenate **"/oauth-callback.html"** to the end of the URL they obtained in step 1.1.13.

_"Note: If you're using repl.it, the redirect URL is the address you obtained in step 1.1.13, with the addition of a location for the OAuth client to return to after the user authorizes, known as the callback page."_

**Comment by goldbergjeffrey** [comment]
@rafaelattux , where is this reference?

**Comment by goldbergjeffrey** [comment]
Complete

**Comment by rafaelattux** [comment]
Validated!
