### ISSUE TITLE
5.1.2 Configure additional embedded objects (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#10]
1. When copying the text from the **ejNeB** object (only in this ID, the others are fine), there's an extra blank space at the end. If this blank space is pasted along, it might cause issues, and some people may not notice it.

2. At the end of this step, remind the user to return to the "JS Analytics" menu.

**Comment by goldbergjeffrey** [comment]
done

**Comment by rafaelattux** [comment]
Validated!
