### ISSUE TITLE
5.3 Embed visualizations using expressions (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#11]
It doesn't render just with this part of the code.

  <qlik-embed
    id="QV04"
    type="barchart"
    fields= "['CategoryName', '=sum(Sales)']"
  ></qlik-embed>
  
  I suggest providing the entire code block here with all the parameters, so users can replace the entire element. This step seems confusing as it is.

**Comment by goldbergjeffrey** [comment]
Waiting for viz on the fly capability to be released for final insert.

**Comment by rafaelattux** [comment]
Hi @goldbergjeffrey , tested again after the release and it's not working (not sure if it's a problem on my end)

![image](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/136381e3-d5de-4619-8cae-8393380151c9)


![image](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/659a2d6a-e168-4512-826b-93b5488aee77)

**Comment by goldbergjeffrey** [comment]
resolved in #18
