### ISSUE TITLE
7.1.1 Set the application id (Not Working)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#12]
This part of the code (as shown in the screenshot) doesn't appear to be correct. In any case, this step doesn't seem to be working.

![app id](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/b7b79a2c-49b0-48e6-9652-8cfe1f914a6b)

**Comment by goldbergjeffrey** [comment]
Yes this is correct. The idea is to set the one that is `let`. Then make sure to fill out host and clientid

**Comment by goldbergjeffrey** [comment]
documented clearly.
