### ISSUE TITLE
7.1.2 Set the host configuration

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#17]
This is not working for me. Is it working for you?

![image](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/604954de-c3be-41ca-a7fb-cefdd521d43e)

![image](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/1370a2ff-d554-4b82-a6ca-464b50fc1347)

And there is also an extra comma at the end on the original project

![image](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/1d23d4d6-f71f-4f69-a82e-a469c2424b4a)

**Comment by goldbergjeffrey** [comment]
I see the issue. Need to add the redirecturi

**Comment by goldbergjeffrey** [comment]
will be addressed by #18
