### ISSUE TITLE
4.1.3 Embed Qlik Sense into the web application (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#5]
In the section below:

4.1.3 Embed Qlik Sense into the web application

_"In the web application, click the **analytics menu** item on the left side of the screen. The Qlik Sense application appears embedded in the window of the web application set to the specified sheet."_

- Adjust the menu name in the tutorial to: "Iframe Analytics," as it appears in the front end.
- Inform the user that at this point in the workshop, only this screen will be working. (Since the homepage will still have an error for now, the user might get confused.)

**Comment by goldbergjeffrey** [comment]
need to change away from iframe analytics because that's not a thing anymore :)
