### ISSUE TITLE
Wrong menus (classic-app.html)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#6]
The menus on the page classic-app.html are incorrect as shown in the screenshot.

![wrong menus](https://github.com/goldbergjeffrey/qlik-embedded-analytics-workshop/assets/54858324/7b4ee5c0-cbcf-4bef-9959-53b7cf9cd639)

**Comment by goldbergjeffrey** [comment]
resolved

**Comment by rafaelattux** [comment]
Validated!
