### ISSUE TITLE
4.1.4 Apply a theme to the embedded application (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#7]
The correct script should include the "id" parameter as it was in the original fork of the project, unless the intention is to remove it or it is deemed unnecessary.

<qlik-embed
  **id="embed-qlik-sense-app"**
  ui="classic/app"
  app-id="<APP_ID>"
  sheet-id="<SHEET_ID>"
  theme="embeddedTheme">
</qlik-embed>

**Comment by goldbergjeffrey** [comment]
The id is no longer needed.
