### ISSUE TITLE
4.1.5 Set a bookmark for the embedded application (Tutorial Suggestion)

### ISSUE THREAD

**Issue by rafaelattux** [goldbergjeffrey/qlik-embedded-analytics-workshop#8]
Suggestion: Create a public bookmark within the application that we will provide and provide the bookmark ID here. This will save many steps in the process (creating, making it public, explaining how to get the ID, etc.).

**Suggested Adjustment:**
Move sections 4.1.4 + 4.1.5 + 4.1.6 to be executed only after completing step 5 (as a bonus stage).

We need to ensure that everyone completes up to step 5 within the 45-minute timeframe. For me, anything after that can be considered a bonus.

We can include a note in the workshop (to skip for now) or simply mention it live if we do not wish to disrupt the sequence.

**Comment by goldbergjeffrey** [comment]
good suggestion. done!
